layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

#projects:
#  sort_by: pushed
#  # sort_by options:
#  #   - pushed
#  #   - stars
#  limit: 9
#  exclude:
#    archived: false
#    forks: false
#    projects:
#     - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: a.iakovliev@icloud.com
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: andrii-iakovliev-81ab0080
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username
  rg: Andrii_Iakovliev

topics:
  - name: R
    web_url: https://github.com/topics/r
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/r/r.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png

  - name: PHP
    web_url: https://github.com/topics/php
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/PHP-logo.svg/1200px-PHP-logo.svg.png

  - name: Laravel
    web_url: https://github.com/topics/laravel
    image_url: https://logos-download.com/wp-content/uploads/2016/09/Laravel_logo.png

  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/javascript/javascript.png

  - name: Node.js
    web_url: https://github.com/topics/node
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/nodejs/nodejs.png

  - name: HTML5
    web_url: https://github.com/topics/html5
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/html/html.png

  - name: Matlab
    web_url: https://github.com/topics/matlab
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/matlab/matlab.png

other:
  - name: Server administration
    web_url: https://github.com/topics/ubuntu
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/ubuntu/ubuntu.png

  - name: Database administration
    web_url: https://github.com/topics/mysql
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/mysql/mysql.png

  - name: Web servers
    web_url: https://github.com/topics/nginx
    image_url: https://raw.githubusercontent.com/github/explore/85cceaeeaf993ca35664dc37ea24f9237fbbfc14/topics/nginx/nginx.png

  - name: Cybersecurity
    web_url: https://gitlab.com/kalilinux
    image_url: https://assets.gitlab-static.net/uploads/-/system/group/avatar/5034914/kali-logo.jpeg?width=64

  - name: IoT
    web_url: https://github.com/topics/raspberrypi
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/raspberry-pi/raspberry-pi.png
